export const REQUESTED_BOARD_CREATE = "REQUESTED_BOARD_CREATE";
export const RECIVED_BOARD_CREATE = "RECIVED_BOARD_CREATE";
export const FAILED_BOARD_CREATE = "FAILED_BOARD_CREATE";

export const REQUESTED_BOARD_UPDATE = "REQUESTED_BOARD_UPDATE";
export const RECIVED_BOARD_UPDATE = "RECIVED_BOARD_UPDATE";
export const FAILED_BOARD_UPDATE = "FAILED_BOARD_UPDATE";

export const REQUESTED_BOARD_DELETE = "REQUESTED_BOARD_DELETE";
export const RECIVED_BOARD_DELETE = "RECIVED_BOARD_DELETE";
export const FAILED_BOARD_DELETE = "FAILED_BOARD_DELETE";
