export const REQUESTD_SIGNUP = "REQUESTD_SIGNUP";
export const RECIVED_SIGNUP = "RECIVED_SIGNUP";
export const FAILED_SIGNUP = "FAILED_SIGNUP";

export const REQUESTD_VERIFY_EMAIL = "REQUESTD_VERIFY_EMAIL";
export const RECIVED_VERIFY_EMAIL = "RECIVED_VERIFY_EMAIL";
export const FAILED_VERIFY_EMAIL = "FAILED_VERIFY_EMAIL";

export const REQUESTD_LOGIN = "REQUESTD_LOGIN";
export const RECIVED_LOGIN = "RECIVED_LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";

